title: "[ §6§lRSocialUI§r ]"
content: "§aSocial \n\n§e- §cFacebook:\n§e- §cInstagram:\n§e- §cYoutube:\n§e- §cDiscord:"
button-close: "§l§dCLOSE\n§7Click to close"
message-close: "§aFollow Social Media Server"

#// In this section you can change it, don't leave it blank //#
                                # I mean the one above! #
#----------#
#Name: RSocialUI #
#Author: RimVG #
#Version:  2.7.1 #
#Api: 5.0.0
#       - 5.15.0
